import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'models/channels.dart';
import 'models/downloaded_items.dart';
import 'models/epg_programmes.dart';
import 'models/episodes.dart';
import 'models/favorites.dart';
import 'models/playlists.dart';
import 'models/radio_stations.dart';
import 'models/series.dart';
import 'models/user_profiles.dart';
import 'models/vod_items.dart';
import 'models/watch_progress.dart';

part 'database.g.dart';

/// Flixium on-device SQLite database (schema v1).
///
/// Generated by `build_runner`. Run:
/// ```sh
/// dart run build_runner build --delete-conflicting-outputs
/// ```
@DriftDatabase(
  tables: [
    Playlists,
    Channels,
    VodItems,
    TvSeries,
    Episodes,
    RadioStations,
    EpgProgrammes,
    Favorites,
    WatchProgressEntry,
    UserProfiles,
    DownloadedItems,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Named constructor for tests -- lets callers supply a custom executor.
  // ignore: avoid_unused_constructor_parameters
  AppDatabase.forTesting(super.e);

  // Bump this when you add / remove tables or alter columns.
  @override
  int get schemaVersion => 5;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.createTable(userProfiles);
          }
          if (from < 3) {
            await m.createTable(downloadedItems);
          }
          if (from < 4) {
            // Add user_id and Xtream credential columns to playlists.
            await m.addColumn(playlists, playlists.userId);
            await m.addColumn(playlists, playlists.username);
            await m.addColumn(playlists, playlists.password);
          }
          if (from < 5) {
            // Add status and progress columns to downloaded_items.
            await m.addColumn(
              downloadedItems,
              downloadedItems.status as GeneratedColumn<Object>,
            );
            await m.addColumn(
              downloadedItems,
              downloadedItems.progress as GeneratedColumn<Object>,
            );
          }
        },
      );

  /// Opens the SQLite database file stored in the app's documents directory.
  static LazyDatabase _openConnection() {
    return LazyDatabase(() async {
      final directory = await getApplicationDocumentsDirectory();
      final file = File(p.join(directory.path, 'flixium_v1.db'));
      return NativeDatabase.createInBackground(file);
    });
  }
}
