name: iflixify-edge
app_id: da_2OPIqt7U7vBW
owner: tsiartasantreas
package: .
env:
  GITHUB_REPO: ${GITHUB_REPO}
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /dl/latest
    - path: /dl/latest/arm64
    - path: /_bootstrap
  cdn_cache:
    enabled: true
debug: false
kind: wasmer.io/App.v0
